### ISSUE TITLE
query gene size as sum of exon lengths from biomaRt

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/hermes#64]
Currently we use the naive way of just calculating `end - start` to populate the `size`. 
Better is something like this:

```r
mart <- biomaRt::useMart("ensembl", dataset = "hsapiens_gene_ensembl")
attrs <- c("ensembl_gene_id", "ensembl_exon_id",
           "chromosome_name", "exon_chrom_start", "exon_chrom_end")
coords <- biomaRt::getBM(filters="entrezgene_id", attributes=attrs, values=c("11185", "10677"), mart=mart)
id <- unique(coords[,"ensembl_gene_id"])
coords <- GRangesList(sapply(id,
# todo: rewrite this part, suggest to put in its own helper function
                             function(i)
                             {
                               i.coords <- coords[coords[,1]== i, 3:5]
                               g <- GRanges(i.coords[,1], IRanges(i.coords[,2],i.coords[,3]))
                               return(g)
                             }), compress=FALSE)
coords <- reduce(coords)
len <- sum(width(coords))
```

To do:
- [x] implement additional helper function `h_get_size_biomart()` based on above prototype code
- [x] test, both with Entrez and with Ensembl IDs
- [x] use accordingly in `h_get_annotation_biomart()` to replace current `start` and `stop` info
- [x] document accordingly in these functions
- [ ] consider mentioning in vignette
